import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Board from '../components/Board'
import Navbar from '../components/Navbar'
import { NewComponentProvider } from '../Context/NewComponentContext'
import Dashboard from '../components/Dashboard'


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NewComponentProvider>
      <Navbar />
      {/* <Dashboard /> */}
      <div className={styles.bg}>
      <Board />
      </div>
      </NewComponentProvider>
    </div>
  )
}

export default Home
