import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Board from '../components/Board'
import Navbar from '../components/Navbar'
import { NewComponentProvider } from '../Context/NewComponentContext'
import { ThemeContext, ThemeProvider } from '../Context/ThemeContext'
import Dashboard from '../components/Dashboard'
import React, { useContext } from 'react'


const Home: NextPage = () => {
  const {toggleTheme} = useContext(ThemeContext)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider>
      <NewComponentProvider>
        
      <Navbar />
      {/* <Dashboard /> */}
      <div className="dark:bg-gray-700">
      <Board />
      </div>
      </NewComponentProvider>
      </ThemeProvider>
    </div>
  )
}

export default Home
